name: Test build

on:
  #push:
    #branches:
      #- master
  workflow_dispatch:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Install Allure command-line tool
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
    - name: Run Schwarzman
      continue-on-error: true
      run: |
        pytest examples/nypl_tests/test_schwarzman.py --alluredir=allure-results --rs --browser=chrome --headless -v -s -n=6 --reruns=2
    - name: Publish Allure report
      uses: simple-report/action-allure-report@v1
      with:
        allure_results: allure-results
        github_token: ${{ secrets.ALLURE }}
